fix attr

diff --git a/bin/zopen-importenvs b/bin/zopen-importenvs
--- a/bin/zopen-importenvs
+++ b/bin/zopen-importenvs
@@ -1,1 +1,103 @@
-ÂÑ>Á>ÎÂ/ËÇíËÁÀÃ?ÊÀÁÎÁ%?ø_Á>ÈÈ?Ë?ÍÊÄÁ/%%ÈÇÁÂ??ÈøÊ?ÀÁ>ÎËÊÁÈÍÊ>ÀÁÎ>Í%%Ë?ÍÊÄÁÀïÇ/ÈÁÌÑÈÄ?ÀÁÀÑÀÈÇ/ÈÅÑÎÁÑÃ$$Ë?ÍÊÄÁÀ>Á))@@$$Ç))ÈÇÁ>ÁÄÇ?:?øÁ>Ñ_ø?ÊÈÁ>ÎË_ÍËÈÂÁË?ÍÊÄÁÀÎÑ/ÈÇÁÀ?ÈËÇÁ%%ÂÍÑ%ÈÑ>ÁÄÇ?íë åá:?øÁ>Ñ_ø?ÊÈÁ>ÎË$ø/ÈÇÈ?ÂÍÑ%ÀÁ>ÎÈ?ÃÁÈÄÇÀÁøÁ>ÀÁ>Ä`)ÁÄÇ?ñÃ>?/ÊÅÍ_Á>ÈÑËËøÁÄÑÃÑÁÀ:?øÁ>Ñ_ø?ÊÈÁ>ÎËÏÑ%%Ë?ÍÊÄÁ/%%Á>ÎÃÑ%ÁËÃÊ?_ç|(á:?øÁ>øÊ?À/>Àç|(á:?øÁ>Â??ÈÁÄÇ?ñÃ/>/ÊÅÍ_Á>ÈÑËËøÁÄÑÃÑÁÀ/>ÀÑÈÊÁøÊÁËÁ>ÈË/ÂÍÑ%ÀÁ>ÎÃÑ%Á:?øÁ>Ñ_ø?ÊÈÁ>ÎËÏÑ%%Ë?ÍÊÄÁÈÇÁ!|&á+^^àá&ëËøÁÄÑÃÑÁÀÀÁøÁ>ÀÁ>ÄÑÁËÃÊ?_ç|(á:?øÁ>øÊ?À/>Àç|(á:?øÁ>Â??ÈÑÃ$$Ë?ÍÊÄÁÀ>Á))ÈÇÁ>ÁÌÑÈÃÑÑÃ$$Ç))ÈÇÁ>ÊÁÈÍÊ>ÃÑÃÑÀÁøË&/ÈÇÇ/ËÈÇÁÀÁÈ/Ñ%Ë?ÃÈÇÁ%?Ä/ÈÑ?>?Ãø?ÊÈËÏÇ?ËÁÁ>ÎÃÑ%ÁË/ÊÁÄ?>ËÍ_ÁÀÃ?ÊË?ÍÊÄÑ>ÅÀÁøË&/ÈÇç|(á:?øÁ>øÊ?À@ç|(á:?øÁ>Â??ÈÑÃÈÇÁ>Í_ÂÁÊ?Ã/ÊÅÍ_Á>ÈËø/ËËÁÀÈ?ËÄÊÑøÈÑËÈÇÁ>ÈÇÁø?ÊÈË/ÊÁÃÁÈÄÇÁÀÃÊ?_ç|(á:?øÁ>øÊ?À/>Àç|(á:?øÁ>Â??ÈÀÑÊÁÄÈ?Ê`ÈÇÁ>ÑÈËÁ>ÎÃÑ%ÁË/ÊÁÃÁÈÄÇÁÀ/>ÀË?ÍÊÄÁÀÑÃÈÇÁ`/ÊÁ>?È/%ÊÁ/À`Ë?ÍÊÄÁÀÑÃ$ÁÉ)ÈÇÁ>ÁÄÇ?ë?ÍÊÄÑ>ÅøÊ?¦ÁÄÈËÃÊ?_ç|(á:?øÁ>øÊ?À/>Àç|(á:?øÁ>Â??È/ÊÊ|ÃàÑÊËÑË/>/ÊÊ/`ÏÇÑÄÇÇ?%ÀËÈÇÁ>/_ÁË?ÃÀÑÊËÏÇ?ËÁÁ>ÎÑËËÁÈÀÁÄ%/ÊÁ//ÊÊ|ÃàÑÊËÍ>ËÁÈ/ÊÊ|ÃàÑÊË$ )<??øÈÇÊ?ÍÅÇ:?øÁ>Â??È:?øÁ>øÊ?ÀÃ?Êø/ÈÇÑ>ÁÄÇ?#ÀÁøË&/ÈÇ'@ËÁÀË@ÅÀ?Ã?ÊÀÁøËÑ>ÃÑ>À#ø/ÈÇ'>/_ÁÁ>ÎÀ?ÀÁøÀÑÊÀÑÊ>/_Á#ÀÁøË'ÀÑÊ+/_ÁÂ/ËÁ>/_Á#ÀÁøÀÑÊ'ñÃÁ>ÎÃÊ?_ÈÇÑËÀÑÊÁÄÈ?Ê`ÑË>?ÈË?ÍÊÄÁÀÈÇÁ>ÃÁÈÄÇÈÇÁÁ>ÎÃÑ%Á/>ÀË?ÍÊÄÁÑÈÑÃ$$#/ÊÊ|ÃàÑÊË$)'=#ÀÑÊ+/_Á'))ÈÇÁ>/ÊÊ/`À?ÁË>ÈÄ?>È/Ñ>ÇÁ>ÄÁË?ÍÊÄÁÈÇÁÁ>ÎÃÑ%ÁÁÄÇ?ëÁÈÈÑ>ÅÍø#ÀÁøÀÑÊ'ÀÁøÁ>ÀÁ>Ä`Á>ÎÑÊ?>_Á>ÈÄÀÀÁøÀÑÊÁ>ÎñÃË?ÍÊÄÑ>ÅÑËËÍÄÄÁËËÃÍ%ÈÇÁ>/ÀÀÈ?/ÊÊ/`ÑÃ$ÁÉ)ÈÇÁ>/ÊÊ|ÃàÑÊËÀÑÊ+/_ÁÃÑÄÀÁ%ËÁÁÄÇ?ë,ÑøøÑ>ÅÈÇÁËÁÈø/ÈÇÀÑÊ+/_Á/ËÑÈÑË/%ÊÁ/À`Ë?ÍÊÄÁÀÃÑÀ?>ÁÀ?>ÁÁ%ËÁñÃø/ÈÇÑËøÊ?ÎÑÀÁÀÈÇÁ>ÂÍÑ%ÁÀÁ>ÎÃÑ%ÁÑËÃÁÈÄÇÁÀÃÊ?_ÈÇÁøÊ?ÎÑÀÁÀø/ÈÇø/ÈÇã?ÊâÍÑ%ÀÑÃ$À#ç|(á':?øÁ>Â??È)$À#ç|(á':?øÁ>øÊ?À)ÈÇÁ>ÁÄÇ?#ç|(á':?øÁ>Â??È#ç|(á':?øÁ>øÊ?ÀÀÑÊÁÄÈ?ÊÑÁËÀ?>?ÈÁÌÑËÈáÌÑÈÑ>ÅÊÁÈÍÊ>ÃÑÑÃ$Ã#ø/ÈÇã?ÊâÍÑ%À'ÂÍÑ%ÀÁ>Î)ÈÇÁ>Í>ËÁÈ!|&á+^åñè^àá&ëÍ>ËÁÈ!|&á+^è êâ <<^àá&ëÍ>ËÁÈ!|&á+^èß&á!|&á+^åñè^àá&ë#ø/ÈÇã?ÊâÍÑ%À'ÂÍÑ%ÀÁ>ÎÁÄÇ?!|&á+^åñè^àá&ë!|&á+^è êâ <<^àá&ë#ø/ÈÇã?ÊâÍÑ%À'ÂÍÑ%ÀÁ>ÎÁÄÇ?!|&á+^è êâ <<^àá&ë!|&á+^èß&á#ø/ÈÇã?ÊâÍÑ%À'ÂÍÑ%ÀÁ>ÎÁÄÇ?!|&á+^èß&áÑÃ$#!|&á+^èß&á'Ìè êâ <<Ì)ÈÇÁ>ÀÁøË#!|&á+^è êâ <<^àá&ë'Á%ËÁÀÁøË#!|&á+^åñè^àá&ë'ÃÑ%??øÈÇÊ?ÍÅÇÈÇÁÀÁøÁ>ÀÁ>ÄÑÁËÂ/ËÁÀ?>ÑÃÑÈÑËÈ/ÊÂ/%%?ÊÅÑÈ/>ÀË?ÍÊÄÁÈÇÁÁ>ÎÃÑ%ÁËÃ?ÊÀÁøÑ>ÀÁøËÀ?Ã/Ñ%ÈÊÍÁÃ?Êø/ÈÇÑ>ÁÄÇ?#ÀÁøË&/ÈÇ'@ËÁÀË@ÅÀ?ÑÃ$Êø/ÈÇ#ÀÁø'Á>Î)ÈÇÁ>Ã/Ñ%Ã/%ËÁÀÁøÀÑÊø/ÈÇ#ÀÁø'ÁÄÇ?ëÁÈÈÑ>ÅÍø#ÀÁøÀÑÊ'ÀÁøÁ>ÀÁ>Ä`Á>ÎÑÊ?>_Á>ÈÄÀ#ÀÁøÀÑÊ'Á>ÎÀ?>?ÈÄÇÁÄ,Ñ>>ÁÌÈÀÁøø/ÈÇ/ËÈÇÁÁ>ÎÃ?ÊÈÇÑËÀÁøÁ>ÀÁ>Ä`ø?ÊÈÑËÃ?ÍÀ>/>ÀË?ÍÊÄÁÀÂÊÁ/,ÃÑÀ?>ÁÑÃÃ/Ñ%ÈÇÁ>ÁÄÇ?í>/Â%ÁÈ?ÃÑ>ÀÁ>ÎÃ?ÊÀÁøÁ>ÀÁ>Ä`#ÀÁø'ÃÑÀ?>ÁÃÑÃÑ
+#!/bin/env bash
+# Used for development to source all the boot/prod .envs
+
+
+(return 0 2>/dev/null) && sourced=1 
+# What exit code did that give?
+if [[ $sourced -ne 1 ]] || [[ "$1" == "-h" ]]
+then
+    echo "zopen-importenvs must be sourced via the . (dot) shell builtin"
+    echo "USAGE: . ./zopen-importenvs [path to buildenv to fetch dependency]"
+    echo "If no argument is specified, zopen-importenvs will source all .env files from $HOME/zopen/prod and $HOME/zopen/boot"
+    echo "If an argument is specified and it represents a buildenv file, zopen-importenvs will source the ZOPEN_*_DEPS specified dependencies from $HOME/zopen/prod and $HOME/zopen/boot"
+    if [[ $sourced -ne 1 ]]; then
+      exit 1     
+    fi
+    if [[ "$1" == "-h" ]]; then
+      return 1     
+    fi
+fi
+
+#depsPath has the details of the location of ports whose env files are consumed for sourcing 
+depsPath="$HOME/zopen/prod|$HOME/zopen/boot"
+
+# if the number of arguments passed to script is 0,
+# then , the ports are fetched from $HOME/zopen/prod and $HOME/zopen/boot directory
+# then its env files are fetched and sourced, if they are not already sourced.
+if [ $# -eq 0 ]
+then
+     echo "Sourcing projects from $HOME/zopen/prod and $HOME/zopen/boot"
+     
+     # arrOfDirs, is an array which holds the names of dirs whose env is set
+     declare -a arrOfDirs
+     unset arrOfDirs[@]
+
+     #Loop through zopen/boot & zopen/prod
+     for path in $(echo ${depsPath} | sed "s/|/ /g") ; do
+         for deps in $(find "${path}" -name ".env")
+         do
+          depdir=$(dirname "${deps}")
+          dirName="$(basename ${depdir})"
+
+          #If env from this directory is not sourced then, fetch the env file and source it 
+          if [[ ! " ${arrOfDirs[*]} " =~ " ${dirName} " ]]; then
+             # array doesn't contain hence, source the env file
+             echo "Setting up ${depdir} dependency environment"
+             cd $depdir
+             . ./.env
+
+             # If sourcing is successful then, add to array
+             if [ $? -eq 0 ]; then
+                arrOfDirs+=($dirName)
+             fi
+             cd - 
+           else
+             echo "Skipping the set path = $dirName, as it is already sourced" 
+           fi
+         done
+      done 
+else 
+    #If path is provided then builedenv file is fetched from the provided path 
+    pathForBuild=$1
+    if [ ! -d "${HOME}/zopen/boot/" ] && [ ! -d "${HOME}/zopen/prod/" ]; then
+       echo "${HOME}/zopen/boot & ${HOME}/zopen/prod directories do not exist. Exiting"
+       return 1 
+    fi
+
+    if [ -f ${pathForBuild}/buildenv ]
+    then
+       unset ZOPEN_GIT_DEPS
+       unset ZOPEN_TARBALL_DEPS
+       unset ZOPEN_TYPE
+ 
+       ZOPEN_GIT_DEPS=$(. ${pathForBuild}/buildenv; echo $ZOPEN_GIT_DEPS); 
+       ZOPEN_TARBALL_DEPS=$(. ${pathForBuild}/buildenv; echo $ZOPEN_TARBALL_DEPS); 
+       ZOPEN_TYPE=$(. ${pathForBuild}/buildenv; echo $ZOPEN_TYPE); 
+       
+       if [ "${ZOPEN_TYPE}x" = "TARBALLx" ]; then
+          deps="${ZOPEN_TARBALL_DEPS}"
+       else
+          deps="${ZOPEN_GIT_DEPS}"
+       fi
+
+       #loop through the dependencies based on if it is tarball or git
+       #and source the env files 
+       for dep in $deps; do
+           fail=true
+           for path in $(echo ${depsPath} | sed "s/|/ /g") ; do
+               if [ -r "$path/${dep}/.env" ]; then
+                  fail=false
+                  depdir="$path/${dep}"
+                  echo "Setting up ${depdir} dependency environment"
+                  cd "${depdir}" && . ./.env 
+
+                  #donot check in next dep path as the env for this dependency port is foudn and sourced.
+                  break;
+               fi
+           done
+           if $fail; then
+              echo "Unable to find .env for dependency ${dep}"
+           fi
+       done 
+    fi
+fi
diff --git a/patch-utils/bin/applypatch b/patch-utils/bin/applypatch
--- a/patch-utils/bin/applypatch
+++ b/patch-utils/bin/applypatch
@@ -1,1 +1,45 @@
-ÂÑ>ËÇèÇÑËÈ??%>ÁÁÀËÈ?ÊÍ>?ÃÃ!ÑÈÊÍ>ËËÍÄÄÁËËÃÍ%%`?>/(/ÄñÈÊÁÉÍÑÊÁËÈÇÁÈ/ÊÂ/%%È?ÂÁÑ>ÈÇÁÀÑÊÁÄÈ?Ê``?ÍÊÍ>ÈÇÑËÃÊ?_ËÁÈÌÑÃ$%È)ÈÇÁ>ÁÄÇ?ë`>È/ÌÈ/ÊÂ/%%ø/ÈÄÇÀÑÊÁÄÇ?ÏÇÁÊÁÈ/ÊÂ/%%>/_ÁÑËÈÇÁ>/_Á?Ã/Ë?ÍÊÄÁÈ/ÊÂ/%%ÁÄÇ?/>Àø/ÈÄÇÀÑÊÑËÈÇÁ>/_Á?Ã/ÀÑÊÁÄÈ?Ê`È?/øø%`ÅÑÈø/ÈÄÇÁËÃÊ?_ÁÌÑÈÃÑÈ/ÊÂ/%%ÅÑÈø/ÈÄÇÀÑÊÈ/ÊÂ/%%ÀÑÊ#È/ÊÂ/%%È/ÊÅ:'ÑÃ$Ã#È/ÊÂ/%%')@@$#È/ÊÂ/%%ÀÑÊ'#È/ÊÂ/%%')ÈÇÁ>ÁÄÇ?è/ÊÂ/%%#È/ÊÂ/%%'À?ÁË>?ÈÁÌÑËÈ?ÊÑË>?ÈÑ>ÈÇÁÃ?Ê_/ÈÃÑ%ÁÈ/ÊÅ:ÁÌÑÈÃÑÑÃ$À#ÅÑÈø/ÈÄÇÀÑÊ')ÈÇÁ>ÁÄÇ?&/ÈÄÇÀÑÊÁÄÈ?Ê`#ÅÑÈø/ÈÄÇÀÑÊ'À?ÁË>?ÈÁÌÑËÈÁÌÑÈÃÑÈ/ÊÂ/%%ÀÑÊÄÀ#È/ÊÂ/%%ÀÑÊ'ÁÄÇ?#&ïà'ÅÑÈø/ÈÄÇÀÑÊÄÀ#ÅÑÈø/ÈÄÇÀÑÊ'ÁÄÇ?#&ïà'Ê_ÊÃ#È/ÊÂ/%%ÀÑÊ'È/ÊÌÎÃ#È/ÊÂ/%%'ÑÃÄÀ#È/ÊÂ/%%ÀÑÊ'ÈÇÁ>ÁÄÇ?áÌÈÊ/ÄÈ?ÃÈ/ÊÂ/%%#È/ÊÂ/%%'ÀÑÀ>?ÈÄÊÁ/ÈÁ#È/ÊÂ/%%ÀÑÊ'ÁÌÑÈÃÑÑÃÅÑÈÑ>ÑÈ@@ÅÑÈ/ÀÀ@@ÅÑÈÄ?__ÑÈ__/Ñ>@@ÅÑÈÄÇÁÄ,?ÍÈÂ?øÁ>ËË%ÈÇÁ>ÁÄÇ?í>/Â%ÁÈ?Ñ>ÑÈÑ/%Ñ:Á/ÅÑÈÊÁø?ËÑÈ?Ê`Ã?ÊÈÇÁÈ/ÊÂ/%%ÁÌÑÈÃÑÃ?ÊøÑ>#ÅÑÈø/ÈÄÇÀÑÊ'ø/ÈÄÇÀ?ÑÃÅÑÈ/øø%`#ø'ÈÇÁ>ÁÄÇ?í>/Â%ÁÈ?/øø%`ø/ÈÄÇ#ø'ÃÊ?_#ÅÑÈø/ÈÄÇÀÑÊ'ÂÊÁ/,ÃÑÀ?>Á
+#!/bin/sh
+#
+# This tool needs to run 'off Z' (it runs successfully on a Mac)
+# It requires the tarball to be in the directory
+# you run this from
+#
+set +x
+if [ $# -lt 2 ]; then
+	echo "Syntax: $0 <tarball> <patch dir>" >&2
+	echo "  where <tarball name> is the name of a source tarball" >&2
+	echo "  and <patch dir> is the name of a directory to apply git patches from" >&2
+	exit 4
+fi
+tarball="$1"
+gitpatchdir="$2"
+tarballdir=${tarball%%.tar.gz}
+if ! [ -f "${tarball}" ] || [ "${tarballdir}" = "${tarball}" ] ; then
+	echo "Tarball ${tarball} does not exist or is not in the format <file>.tar.gz " >&2
+	exit 4
+fi
+
+if ! [ -d "${gitpatchdir}" ]; then
+	echo "Patch directory ${gitpatchdir} does not exist" >&2
+	exit 4
+fi
+tarballdir=$(cd ${tarballdir} && echo ${PWD})
+gitpatchdir=$(cd ${gitpatchdir} && echo ${PWD})
+
+rm -rf "${tarballdir}"
+tar -xvf "${tarball}"
+if ! cd "${tarballdir}"; then
+	echo "Extract of tarball ${tarball} did not create ${tarballdir}" >&2
+	exit 4
+fi
+if ! git init || ! git add . || ! git commit -m "main" || ! git checkout -b openssl ; then
+	echo "Unable to initialize a git repository for the tarball" >&2 
+	exit 4
+fi
+
+for p in ${gitpatchdir}/*.patch; do
+	if ! git apply "${p}"; then
+		echo "Unable to apply patch ${p} from ${gitpatchdir}" >&2
+		break
+	fi
+done
diff --git a/patch-utils/bin/dopatch b/patch-utils/bin/dopatch
--- a/patch-utils/bin/dopatch
+++ b/patch-utils/bin/dopatch
@@ -1,1 +1,29 @@
-ÂÑ>ËÇËÑ_ø%ÁÍÈÑ%ÑÈ`È?/øø%`/ÈÊ/ÀÑÈÑ?>/%ø/ÈÄÇ_Á/>ÈÈ?ÂÁÊÍ>?>(/ÄËÁÈÌÑÃ$%È)ÈÇÁ>ÁÄÇ?ë`>È/Ìø/ÈÄÇÀÑÊø/ÈÄÇÃÑ%ÁÁÄÇ?/>Àø/ÈÄÇÀÑÊÑËÈÇÁ>/_Á?Ã/ÀÑÊÁÄÈ?Ê`È?/øø%`ËÈ/>À/ÊÀø/ÈÄÇÈ?ÁÄÇ?/>Àø/ÈÄÇÑËÈÇÁø/ÈÄÇÃÑ%ÁÈ?/øø%`ÁÌÑÈÃÑø/ÈÄÇÀÑÊø/ÈÄÇÑÃ$Ã#ø/ÈÄÇÀÑÊ'#ø/ÈÄÇ')ÈÇÁ>ÁÄÇ?&/ÈÄÇÃÑ%Á#ø/ÈÄÇ'À?ÁË>?ÈÁÌÑËÈÁÌÑÈÃÑÑÃ$À#ø/ÈÄÇÀÑÊ')ÈÇÁ>ÁÄÇ?&/ÈÄÇÀÑÊÁÄÈ?Ê`#ø/ÈÄÇÀÑÊ'À?ÁË>?ÈÁÌÑËÈÁÌÑÈÃÑÑÃø/ÈÄÇÀÊ`ÊÍ>ø#ø/ÈÄÇÀÑÊ'#ø/ÈÄÇ'ÈÇÁ>ÁÄÇ?í>/Â%ÁÈ?øÁÊÃ?Ê_ø/ÈÄÇÃ?Ê#ø/ÈÄÇÀÑÊ'#ø/ÈÄÇ'ÁÌÑÈÃÑø/ÈÄÇø#ø/ÈÄÇÀÑÊ'#ø/ÈÄÇ'
+#!/bin/sh
+#
+# simple utility to apply a traditional patch (meant to be run on Mac)
+#
+set +x
+if [ $# -lt 2 ]; then
+        echo "Syntax: $0 <patch dir> <patch file>" >&2
+        echo "  and <patch dir> is the name of a directory to apply standard patch to" >&2
+        echo "  and <patch> is the patch file to apply" >&2
+        exit 4
+fi
+patchdir="$1"
+patch="$2"
+if ! [ -f "${patchdir}/${patch}" ] ; then
+        echo "Patch file ${patch} does not exist " >&2
+        exit 4
+fi
+
+if ! [ -d "${patchdir}" ]; then
+        echo "Patch directory ${patchdir} does not exist" >&2
+        exit 4
+fi
+
+if ! patch --dry-run -p1 <"${patchdir}/${patch}"; then
+	echo "Unable to perform patch for ${patchdir}/${patch}" >&2
+	exit 4
+fi
+
+patch -p1 <"${patchdir}/${patch}"
diff --git a/patch-utils/bin/extractpatch b/patch-utils/bin/extractpatch
--- a/patch-utils/bin/extractpatch
+++ b/patch-utils/bin/extractpatch
@@ -1,1 +1,41 @@
-ÂÑ>ËÇÁÌÈÊ/ÄÈ/ø/ÈÄÇ?ÍÈ?Ã/ø/ÈÄÇËÁÈÏÑÈÇÈÇÁÃ?Ê_ÊÁ%/ÈÑÎÁÃÑ%Á>/_Á%Ñ>Á>Í_ÂÁÊÁÅÄÊ`øÈ?øøÄÄ/øÄËÁÈÌÑÃ$>Á)ÈÇÁ>ÁÄÇ?ë`>È/Ìø/ÈÄÇø/ÈÄÇËÁÈÁÌÑÈÃÑø/ÈÄÇø/ÈÄÇËÁÈÃÑ%Á#ø/ÈÄÇ'%Ñ>Á#ø/ÈÄÇ'ËÈ/ÊÈ-ÅÊÁø>;#ø/ÈÄÇËÁÈ'@ÅÊÁø#ÃÑ%Á'-ËÈ/ÊÈÃÑ%Á%Ñ>Á#ËÈ/ÊÈ'ÑÃ$#ËÈ/ÊÈÃÑ%Á%Ñ>Á'ÌÌ)ÈÇÁ>ÁÄÇ?ä?Í%À>?ÈÃÑ>Àø/ÈÄÇËÁÈ#ø/ÈÄÇËÁÈ'ÁÌÑÈÃÑËÈ/ÊÈ-È/Ñ%#ËÈ/ÊÈÃÑ%Á%Ñ>Á'#ø/ÈÄÇËÁÈ'@ÅÊÁø>  #%Ñ>Á'-ÊÁ%/ÈÑÎÁËÈ/ÊÈø/ÈÄÇ%Ñ>Á#ËÈ/ÊÈ'ÑÃ$#ÊÁ%/ÈÑÎÁËÈ/ÊÈø/ÈÄÇ%Ñ>Á'ÌÌ)ÈÇÁ>ÁÄÇ?ä?Í%À>?ÈÃÑ>Àø/ÈÄÇËÁÈ#ø/ÈÄÇËÁÈ'%Ñ>Á#%Ñ>Á'ÁÌÑÈÃÑËÈ/ÊÈø/ÈÄÇ%Ñ>ÁËÈ/ÊÈÃÑ%Á%Ñ>ÁÊÁ%/ÈÑÎÁËÈ/ÊÈø/ÈÄÇ%Ñ>ÁËÈ/ÊÈËÁ/ÊÄÇ%Ñ>ÁËÈ/ÊÈø/ÈÄÇ%Ñ>ÁÁ>À-È/Ñ%#ËÈ/ÊÈËÁ/ÊÄÇ%Ñ>Á'#ø/ÈÄÇËÁÈ'@ÅÊÁø>  -ÊÁ%/ÈÑÎÁÁ>Àø/ÈÄÇ%Ñ>Á#Á>À'ÑÃ$#ÊÁ%/ÈÑÎÁÁ>Àø/ÈÄÇ%Ñ>Á'ÌÌ)ÈÇÁ>Á>Àø/ÈÄÇ%Ñ>Á-ÏÄ%#ø/ÈÄÇËÁÈ'@/Ï,#øÊÑ>È'-ÊÁ%/ÈÑÎÁÁ>Àø/ÈÄÇ%Ñ>ÁÁ>Àø/ÈÄÇ%Ñ>ÁËÈ/ÊÈø/ÈÄÇ%Ñ>ÁÃÑÈ/Ñ%#ËÈ/ÊÈø/ÈÄÇ%Ñ>Á'#ø/ÈÄÇËÁÈ'@ÇÁ/À#ÊÁ%/ÈÑÎÁÁ>Àø/ÈÄÇ%Ñ>Á'
+#!/bin/sh
+#
+# extract a patch out of a patch set with the form:
+#   <relative-file-name>:<line-number>, e.g.
+#   crypto/ppccap.c:209 
+#
+set +x
+if [ $# -ne 2 ]; then
+	echo "Syntax: $0 <patch> <patch-set>" 
+	exit 4
+fi
+patch="$1"
+patchset="$2"
+
+file=${patch%%:*}
+line=${patch##*:}
+
+start=`grep -n '^---' "${patchset}" | grep "${file}"` 
+startfileline=${start%%:*}
+if [ "${startfileline}x" = "x" ]; then
+	echo "Could not find patch set ${patchset}" 
+	exit 4
+fi
+
+start=`tail +${startfileline} "${patchset}" | grep -n "@@ -${line},"`
+relativestartpatchline=${start%%:*}
+if [ "${relativestartpatchline}x" = "x" ]; then
+	echo "Could not find patch set ${patchset}, line ${line}" 
+	exit 4
+fi
+startpatchline=$((startfileline+relativestartpatchline))
+startsearchline=$((startpatchline+1))
+
+end=`tail +${startsearchline} "${patchset}" | grep -n "@@ -"`
+relativeendpatchline=${end%%:*}
+if [ "${relativeendpatchline}x" = "x" ]; then
+	endpatchline=`wc -l "${patchset}" | awk '{ print $1 }'`
+	relativeendpatchline=$((endpatchline-startpatchline+1))
+fi
+
+tail +${startpatchline} "${patchset}" | head -${relativeendpatchline}
